import { jsPDF } from "jspdf";
import type { AnalysisResult } from "./geminiService";

export function generateAnalysisReport(result: AnalysisResult) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text(`Resume Intelligence Report`, 20, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by Gemini Dual-Lens Engine`, 20, 26);

    // Line Separator
    doc.setDrawColor(200);
    doc.line(20, 32, pageWidth - 20, 32);

    let y = 45;

    // VERDICT
    doc.setFont("helvetica", "italic");
    doc.setFontSize(12);
    doc.setTextColor(60);
    const splitVerdict = doc.splitTextToSize(`"${result.summary_verdict}"`, pageWidth - 40);
    doc.text(splitVerdict, 20, y);
    y += (splitVerdict.length * 7) + 10;

    // SCORES
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`ATS Compatibility: ${result.scores.ats_compatibility}%`, 20, y);
    doc.text(`Recruiter Impact: ${result.scores.recruiter_impact}%`, pageWidth / 2, y);
    y += 15;

    // ATS WARNINGS (If any)
    if (result.ats_warnings.length > 0) {
        doc.setFontSize(12);
        doc.setTextColor(185, 28, 28); // Red
        doc.text("ATS Formatting Alerts:", 20, y);
        y += 7;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        result.ats_warnings.forEach(warn => {
            doc.text(`• ${warn}`, 25, y);
            y += 6;
        });
        y += 5;
    }

    // MISSING KEYWORDS
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Critical Keyword Gaps:", 20, y);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    if (result.critical_missing_keywords.length > 0) {
        const keywordsStr = result.critical_missing_keywords.join(", ");
        const splitKeywords = doc.splitTextToSize(keywordsStr, pageWidth - 40);
        doc.text(splitKeywords, 20, y);
        y += (splitKeywords.length * 6) + 10;
    } else {
        doc.text("None detected.", 20, y);
        y += 10;
    }

    // IMPROVEMENTS TABLE-LIKE LIST
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Strategic Improvements:", 20, y);
    y += 10;

    doc.setFontSize(10);
    result.resume_improvements.forEach((item) => {
        // Check for page break
        if (y > 270) {
            doc.addPage();
            y = 20;
        }

        doc.setFont("helvetica", "bold");
        doc.text(`[${item.section}] ${item.issue}`, 20, y);
        y += 5;

        doc.setFont("helvetica", "normal");
        const splitFix = doc.splitTextToSize(`Fix: ${item.fix}`, pageWidth - 30);
        doc.text(splitFix, 25, y);
        y += (splitFix.length * 5) + 8;
    });

    doc.save("resume-dual-lens-report.pdf");
}
